qa.url=https://parabank.parasoft.com/parabank/index.htm
dev.url=https://dev.parabank.parasoft.com/parabank/index.htm
staging.url=https://staging.parabank.parasoft.com/parabank/index.htm
timeout=10
browser=chrome
headless=false
env=QA